name: Release - Publish on PowershellGallery
on:
  release:
    types: [released]
jobs:
  publish-powershellgallery:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.4
      with: 
        tag: "${{ github.event.release.tag_name }}"
        fileName: "PSBicepApiManagement.zip"
        tarBall: false
        zipBall: false
        
    - name: Publishing
      run: |
        Expand-Archive ./PSBicepApiManagement.zip ./filesToPublish
        
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
        Import-LocalizedData -BaseDirectory "./filesToPublish/PSBicepApiManagement" -FileName "PSBicepApiManagement.psd1" -BindingVariable manifest
        foreach($moduleName in $manifest.RequiredModules){
            if($moduleName -is [hashtable]){
                $requiredModuleName = $moduleName.ModuleName
                $requiredModuleVersion = $moduleName.Version
                Install-Module -Name $requiredModuleName -RequiredVersion $requiredModuleVersion -Force -Confirm:$false
            }
            else{
                Install-Module -Name $moduleName -Force -Confirm:$false
            }
        }

        Publish-Module -Path './filesToPublish/PSBicepApiManagement' -NuGetApiKey ${{ secrets.PSGALLERYAPIKEY }}
      shell: pwsh