name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.4
      with: 
        tag: "${{ github.event.release.tag_name }}"
        fileName: "PSBicepApiManagement.zip"
        tarBall: false
        zipBall: false
        
    - name: Publishing
      run: |
        Expand-Archive ./PSBicepApiManagement.zip ./filesToPublish
        Publish-Module -Path './filesToPublish/PSBicepApiManagement' -NuGetApiKey ${{ secrets.PSGALLERYAPIKEY }}
      shell: pwsh