name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.4
      with: 
        latest: true
        fileName: "PSBicepApiManagement.zip"
        tarBall: false
        zipBall: false
        
    - name: Publishing
      run: |
        Expand-Archive .\output\PSBicepApiManagement.zip .\output\
        Publish-Module -Path './filesToPublish' -NuGetApiKey ${{ secrets.PSGALLERY }}
      shell: pwsh