name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          file: '*'
          target: ./
        
      - name: Publishing
        run: |
          Expand-Archive .\output\PSBicepApiManagement.zip .\output\
          Publish-Module -Path './filesToPublish' -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh